### ISSUE TITLE
gfhost -lv - connection refused

### ISSUE THREAD

**Issue by WGandy** [oss-tsukuba/gfarm#1132]
I have executed 
`$ sudo config-gfsd`
And received 
`config-gfsd success`

I have also executed 
`$ /usr/bin/gfhost -c -a x86_64-linuxmint20.3-linux -p 600 -n 4 <myhost>`
and
`$  systemctl start gfsd.service`
and received
`==== AUTHENTICATION COMPLETE ===`

The secret key has been copied to the host admin user's home folder and has ownership changed to the host admin user

When I run 
`gfhost -lv`
I receive
```
-.--/-.--/-.-- - x86_64-linuxmint20.3-linux 4 <myhost> 600 0(127.0.1.1)
<myhost>: connection refused
```

**Comment by WGandy** [comment]
To add to this... 

I tried adding another host entry with the local IP address instead of host name (I don't have dns on the local network anyway for remote hosts to connect). 
```
$ /usr/bin/gfhost -c -a x86_64-linuxmint20.3-linux -p 600 -n 4 127.0.0.1
$ gfhost -lv
0.00/0.00/0.00 s x86_64-linuxmint20.3-linux 4 127.0.0.1 600 0(127.0.0.1)
-.--/-.--/-.-- - x86_64-linuxmint20.3-linux 4 <myhost> 600 0(127.0.1.1)
<myhost>: connection refused
```
It seems to indicate that the 127.0.0.1 is actually up and working. So then I tried to delete the host entry with the hostname. 
`$ /usr/bin/gfhost -d <myhost>`

```
$ gfhost -lv
-.--/-.--/-.-- - x86_64-linuxmint20.3-linux 4 127.0.0.1 600 0(127.0.0.1)
127.0.0.1: connection refused
```

**Comment by otatebe** [comment]
Please check the gfsd is running on the host.  Also, syslog helps to understand what happens.  Would you paste the  corresponding part of syslog?

Also, if you add 'log_level debug' to ~/.gfarm2rc, you can see the debug message.

**Comment by WGandy** [comment]
Yes, gfsd is running. 

Here are the last lines of the syslog although the last 2 lines have repeated a couple times. 

```
Mar 12 05:56:44 <myuser> gfmd[2206]: <info> [1005044] number of ongoing replications: 0
Mar 12 05:56:44 <myuser> gfmd[2206]: <info> [1005098] cumulative replication progress: 0 bytes / 0 files 0 seconds
Mar 12 05:57:07 <myuser> gfmd[2206]: <notice> [1000044] (<myuser>@localhost) authenticated: auth=sharedsecret local_user=<myuser>
Mar 12 05:57:07 <myuser> gfmd[2206]: <notice> [1000286] (<myuser>@localhost) disconnected
```
Since gfarm2rc doesn't appear to be in use I added the log_level debug line to /etc/gfarm2.conf

```
$ gfhost -lv
libgfarm: <debug> [1001248] read or receive operation from socket failed: Connection refused
-.--/-.--/-.-- - x86_64-ubuntu20.04-linux 2 <myuser> 600 0(127.0.1.1)
<myuser>: connection refused 
```

It seems like this is caused by a simple issue. But I just haven't been able to recognize it yet.

**Comment by otatebe** [comment]
Thanks for the information.  For the local access, Gfarm uses the unix domain socket instead of tcp socket.  Your first execution of gfsd for <myhost> creates unix domain sockets for all addresses.  The next execution of gfsd for 127.0.0.1 cannot creates unix domain sockets due to alread used.  This is a problem.  This should be resolved by restarting the gfsd.

**Comment by WGandy** [comment]
Aha! unix domain socket! 

Restarting the machine altogether appears to have cleared this issue. Restarting gfsd without rebooting did not appear to fix it but further testing would be necessary to confirm.

**Comment by n-soda** [comment]
Close this ticket,
because the problem seems to be resolved
and it has been over a year since last conversation
